


server:
  port: 80
  servlet:
    context-path: /demo
spring:
  datasource:
    driver-class-name: @mysql.derive@
    username: @mysql.username@
    password: @mysql.password@
    url: @mysql.url@
  redis:
    host: @redis.host@
    database: @redis.database@

  data:
    mongodb:
      host: @mongo.host@
      database: @mongo.database@
      port: @mongo.port@
  rabbitmq:
    host: @rabbitmq.host@
    port: @rabbitmq.port@
    virtual-host: @rabbitmq.virtual-host@
    publisher-confirm-type: correlated
    username: @rabbitmq.username@
    password: @rabbitmq.password@
  profiles:
    include: pro
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis:
  mapper-locations: classpath:mapper/*.xml

minio:
  endpoint: '@minio.endpoint@'
  bucketName: '@minio.bucketName@'
  accessKey: '@minio.accessKey@'
  secretKey: '@minio.secretKey@'